---
title: "readme_plots"
author: "finn krauss"
date: "2025-05-24"
output: md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The Folder "plots" contains plots generated inside the R code of this project.

-   **component_map** show a bathymetric map of the North Sea and the area of each component adapted from Payne 2010 & Dickey-Collas et al. 2009.
-   **env_grid** shows a grid of time-series of the environmental data (Sea-Surface-Temperature, Sea-Bottom-Temperature & Sea-Surface-Salinity and prey abundance) of the individual spawning components. They contain yearly averages for the area mapped in "component_map".
-   **hysteresis\_** shows the relationship Spawning-Stock-Biomas (SSB) to Fishingmortality (F) pattern of hysteresis for the full stock and individual components.
-   **LAI_by_year** shows the time-series of the Larvae-Abundance-Index (LAI) for each spawning component.
-   **LAI_percent** shows the percentage of the total LAI each component contributes over time.
-   **SRR\_** plots the Stock-Recruitment-Relationship, SSB vs Recruitment (R) for the full stock and individual components.
-   **SSB_cpt\_** shows the SSB for each area over time including calculated change-points and corresponding phases.
