---
title: "data cleanup"
author: "finn krauss"
date: "2025-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

# Load packages

```{r}
setwd("~/R Studio/NSAS Herring/NSAS-Herring")

library(dplyr)
library(tidyverse)
library(ncdf4)
library(raster)
library(ggplot2)
library(reshape2)
```

# Load and clean files

## LAI data import

```{r}
## Read LAI .txt data, rename its columns & convert from century break to full year
LAI_full <- read.table("data raw/NSAS LAI.txt", header = TRUE, strip.white = TRUE) %>%
  rename(component = Area, 
         year = Year, 
         LAI_unit = LAIUnit, 
         fortnight = Fortnight, 
         LAI_9mm = L..9) %>%
  mutate(year = ifelse(year >= 100, 2000 + (year - 100),1900 + year),
         component = case_when(component == "Or/Sh" ~ "Shetland_Orkney", 
                               component == "CNS" ~ "Banks",
                               component == "SNS" ~ "Downs", 
                               TRUE ~ component),
         component = as.factor(component),
         LAI_unit = as.factor(LAI_unit),
         fortnight = as.factor(fortnight))

## Read LAI_components .csv, convert it into longformat & rename columns for continuity
LAI_component <- read_csv("data raw/NSAS LAI Components 2025.csv") %>%
  pivot_longer(cols = -c(1), names_to = "year", values_to = "LAI_perc.") %>%
  rename(component = ...1) %>%
  mutate(component = case_when(component == "LAI-ORSH" ~ "Shetland_Orkney",
                               component == "LAI-BUN" ~ "Buchan",
                               component == "LAI-CNS" ~ "Banks",
                               component == "LAI-SNS" ~ "Downs"),
         component = as.factor(component),
         year = as.numeric(year),
         LAI_perc. = LAI_perc. * 100)

## Read SSB_2025 .csv & and rename columns for continuity
SSB_full <- read_csv("data raw/NSAS SSB 2025.csv") %>%
  dplyr::select(-1) %>%
  rename(SSB = value, cv = CV, l_bnd = lbnd, u_bnd = ubnd)  

  ### *(SSB = SSB in Tonnes, cv = coefficient of variation, l_bnd = lower limit of 95% CI & u_bnd = upper limit of 95% CI)

## Split SSB Data by components & 95% bounds by component percentage and attach it and LAI percent data to SSB
SSB_LAI <- SSB_full %>%
  left_join(LAI_component, by = "year") %>%
  mutate(SSB_by_component = SSB * (LAI_perc. / 100),
         l_bnd = l_bnd * (LAI_perc. / 100),
         u_bnd = u_bnd * (LAI_perc. / 100)) %>%
  drop_na()
```

## Environmental .nc data import

```{r}
## Build function for importing and combining .nc files
load_environmental_data <- function(sst_file, sbt_file, sss_file) {
  ### Load SST data
  nc_sst <- nc_open(sst_file)
  sst_data_raw <- ncvar_get(nc_sst, "thetao")
  lon <- ncvar_get(nc_sst, "longitude")
  lat <- ncvar_get(nc_sst, "latitude")
  time_raw <- ncvar_get(nc_sst, "time")
  nc_close(nc_sst)

  ### Load SBT data
  nc_sbt <- nc_open(sbt_file)
  sbt_data_raw <- ncvar_get(nc_sbt, "bottomT")
  nc_close(nc_sbt)

  ### Load SSS data
  nc_sss <- nc_open(sss_file)
  sss_data_raw <- ncvar_get(nc_sss, "so")
  nc_close(nc_sss)

  ### Handle NAs
  sst_data_raw[is.nan(sst_data_raw)] <- NA
  sst_data_raw[sst_data_raw == -32768] <- NA

  sbt_data_raw[is.nan(sbt_data_raw)] <- NA
  sbt_data_raw[sbt_data_raw == -32768] <- NA

  sss_data_raw[is.nan(sss_data_raw)] <- NA
  sss_data_raw[sss_data_raw == -32768] <- NA

  ### Handle time
  ### Re-open nc_sst to get time attributes, or ensure it's passed/stored if needed
  temp_nc_sst <- nc_open("data raw/NS SST Monthly.nc")
  time_units <- ncatt_get(temp_nc_sst, "time", "units")$value
  nc_close(temp_nc_sst)

  time_origin <- sub("seconds since ", "", time_units)

  dates <- as.Date(time_raw / (24 * 60 * 60), origin = time_origin)
  years <- as.numeric(format(dates, "%Y"))
  months <- as.numeric(format(dates, "%m"))

  ### Combine into a single structure
  env_data_full <- list(
    SST = sst_data_raw,
    SBT = sbt_data_raw,
    SSS = sss_data_raw,
    lon = lon,
    lat = lat,
    years = years,
    months = months,
    dates = dates)

  return(env_data_full)}

## Call function and store in environment
env_data_full <- load_environmental_data("data raw/NS SSt Monthly.nc", "data raw/NS SBT Monthly.nc", "data raw/NS SSS Monthly.nc")
```

### Splitting environmental & SSB data by components

```{r}

## Build Function to subset environmental data by components
subset_environmental_data <- function(combined_data) {

  ### Load coords_components
  coords_components <- read_csv("data raw/coords_components.csv")

  ### Initialise list
  environmental_subsets_by_area <- list()

  ### Loop through each area defined in coords_components
  for (i in 1:nrow(coords_components)) {
    area_name <- coords_components$component[i]
    lon_min <- coords_components$lon_min[i]
    lon_max <- coords_components$lon_max[i]
    lat_min <- coords_components$lat_min[i]
    lat_max <- coords_components$lat_max[i]

    ### Find the indices of long & lat that fall within the areas bounds
    ### Use 'combined_data$' to access elements of the passed list
    lon_indices <- which(combined_data$lon >= lon_min & combined_data$lon <= lon_max)
    lat_indices <- which(combined_data$lat >= lat_min & combined_data$lat <= lat_max)

    ### Subset the 3D environmental arrays using the identified indices
    ### Use 'combined_data$' to access elements of the passed list
    subset_env_list <- list(
      SST = combined_data$SST[lon_indices, lat_indices, ],
      SBT = combined_data$SBT[lon_indices, lat_indices, ],
      SSS = combined_data$SSS[lon_indices, lat_indices, ],
      lon = combined_data$lon[lon_indices],
      lat = combined_data$lat[lat_indices],
      years = combined_data$years,
      months = combined_data$months,
      dates = combined_data$dates)

    ### Store data in the 'environmental_subsets_by_area' list
    environmental_subsets_by_area[[area_name]] <- subset_env_list}

  return(environmental_subsets_by_area)}

## Call the function and store result in environment
env_data_subset <- subset_environmental_data(env_data_full)
```

# First visual investigation

## LAI data visualization

```{r}
## Plot timeseries of LAI by component

### Add LAI by year
LAI_aggregated <- LAI_full %>%
  group_by(year, component) %>%
  summarise(LAI_9mm_sum = sum(LAI_9mm),
    .groups = 'drop')
  
### Plot aggregated LAI
plot_LAI_byyear <- ggplot(LAI_aggregated, aes(x = year, 
                    y = LAI_9mm_sum, 
                    group = component)) +
  geom_line(color = "navyblue", linewidth = 0.8) +
  geom_smooth(color = "steelblue", linewidth = 0.8) +
  facet_wrap(~ component, ncol = 2, scales = "free_y") +
  labs(title = "Agregated Larvae Abundance Index (LAI) by Unit Area over Years", 
       x = "Year", 
       y = "LAI (Larvae Abundance Index) >= 9mm") +
  theme_minimal()
print(plot_LAI_byyear)

## Plot stacked bar chart for components percentage of LAI
plot_LAI_percent <- ggplot(LAI_component, aes(x = as.factor(year), 
                              y = LAI_perc., fill = component)) +
  geom_bar(stat = "identity", position = "stack") + # Create stacked bars
  labs(title = "Percentage of Larvae Abundance Index (LAI) by Component and Year",
       x = "Year",
       y = "LAI Percentage (%)",
       fill = "Component") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10))) +
  scale_fill_viridis_d()
print(plot_LAI_percent)

## Plot timeseries of SSB including confindence bounds
plot_SSB_full <- ggplot(SSB_full, aes(x = year)) +
  geom_ribbon(aes(ymin = (l_bnd / 1000000), 
                  ymax = (u_bnd / 1000000)), fill = "skyblue", alpha = 0.5) +
  geom_line(aes(y = (SSB / 1000000)), color = "navyblue", linewidth = 1) +
  labs(title = "SSB with 95% Confidence Bounds", 
       x = "Year", 
       y = "SSB in million t") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)))
print(plot_SSB_full)

## Visualise subset SSB data by component
plot_SSB_component <- ggplot(SSB_LAI, aes(x = year, 
                           y = (SSB_by_component / 1000000))) +
  geom_ribbon(aes(ymin = (l_bnd / 1000000), ymax = (u_bnd / 1000000)), fill = "skyblue", alpha = 0.5) +
  geom_line(color = "navyblue", linewidth = 0.8) +
  facet_wrap(~ component, ncol = 2, scales = "fixed") +
  labs(title = "SSB with 95% Confidence Bounds by Component over Years",
       x = "Year",
       y = "SSB in million tonnes by Component") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_text(margin = margin(t = 10)),
        axis.title.y = element_text(margin = margin(r = 10)))
print(plot_SSB_component)
```

## Environmental data visualization

```{r}

## Build function to plot environmental data
plot_environmental_ts <- function(data_list, plot_area_title) {
  
  ### Extract variables from the input list
  sst_data_raw <- data_list$SST
  sbt_data_raw <- data_list$SBT
  sss_data_raw <- data_list$SSS
  dates <- data_list$dates
  years <- data_list$years
  months <- data_list$months
  
  ### Calculate overall time series by averaging across the third dimension
  overall_sst_ts <- apply(sst_data_raw, 3, mean, na.rm = TRUE)
  overall_sbt_ts <- apply(sbt_data_raw, 3, mean, na.rm = TRUE)
  overall_sss_ts <- apply(sss_data_raw, 3, mean, na.rm = TRUE)

  ### Create a data frame for monthly time series plotting
  overall_ts_df <- data.frame(
    Date = dates,
    Year = years,
    Month = months,
    SST = overall_sst_ts,
    SBT = overall_sbt_ts,
    SSS = overall_sss_ts)

  ### Calculate yearly averages from the monthly data
  yearly_avg_df <- overall_ts_df %>%
    group_by(Year) %>%
    summarise(
      SST = mean(SST, na.rm = TRUE),
      SBT = mean(SBT, na.rm = TRUE),
      SSS = mean(SSS, na.rm = TRUE),
      .groups = 'drop') %>%
    mutate(Date = as.Date(paste0(Year, "-06-06")))

  ### Melt the data frames for easier plotting with ggplot2 (one 'value' column)
  overall_ts_melted <- melt(overall_ts_df, id.vars = c("Date", "Year", "Month"),
                            variable.name = "Variable", value.name = "Value_Monthly")

  yearly_avg_melted <- melt(yearly_avg_df, id.vars = c("Date", "Year"),
                            variable.name = "Variable", value.name = "Value_Yearly")

  ### Plot overall time series with yearly averages overlayed
  p <- ggplot(overall_ts_melted, aes(x = Date, y = Value_Monthly, color = Variable)) +
    geom_line(alpha = 0.8) +
    geom_smooth(data = yearly_avg_melted, aes(x = Date, 
                                              y = Value_Yearly, 
                                              color = Variable), size = 1.2) +
    labs(title = paste(plot_area_title, " Environmental Conditions (Monthly & Yearly Averages)"),
         y = "Value",
         x = "Date") +
    theme_minimal() +
    scale_color_manual(values = c("SST" = "red", "SBT" = "blue", "SSS" = "darkgreen")) +
    facet_wrap(~ Variable, scales = "free_y", ncol = 1) +
    theme(legend.position = "none")
  
  return(p)}

## Call function and plot combined data
plot_env_data_full <- plot_environmental_ts(env_data_full, "Overall North Sea")
print(plot_env_data_full)

## Plot subset data into a grid
plot_env_data_Shetland_Orkneys <- plot_environmental_ts(env_data_subset$Shetland_Orkney, "Shetland / Orkney")
plot_env_data_Buchan <- plot_environmental_ts(env_data_subset$Buchan, "Buchan")
plot_env_data_Banks <- plot_environmental_ts(env_data_subset$Banks, "Banks")
plot_env_data_Downs <- plot_environmental_ts(env_data_subset$Downs, "Downs")

print(plot_env_data_Shetland_Orkneys)
print(plot_env_data_Buchan)
print(plot_env_data_Banks)
print(plot_env_data_Downs)
```

# Save data and plots

## Save rdata

```{r}
### LAI data
save(LAI_full, file = file.path("data/", "LAI_full.Rdata"))
save(LAI_aggregated, file = file.path("data/", "LAI_aggregated.Rdata"))
save(SSB_LAI, file = file.path("data/", "SSB_LAI.Rdata"))


# Environmental data
save(env_data_full, file = file.path("data/", "env_data_full.Rdata"))
save(env_data_subset, file = file.path("data/", "env_data_subset.Rdata"))
```

## Save plots

```{r}
### LAI plots
ggsave(filename = file.path("plots/", "LAI_by_year.png"),
       plot = plot_LAI_byyear,
       bg = "white",
       width = 15,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "LAI_percent.png"),
       plot = plot_LAI_percent,
       bg = "white",
       width = 15,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "SSB_component.png"),
       plot = plot_SSB_component,
       bg = "white",
       width = 15,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "SSB.png"),
       plot = plot_SSB_full,
       bg = "white",
       width = 15,
       height = 10,
       dpi = 300)

### Env. plots
ggsave(filename = file.path("plots/", "env_NS.png"),
       plot = plot_env_data_full,
       bg = "white",
       width = 10,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "env_Banks.png"),
       plot = plot_env_data_Banks,
       bg = "white",
       width = 10,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "env_Buchan.png"),
       plot = plot_env_data_Buchan,
       bg = "white",
       width = 10,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "env_Downs.png"),
       plot = plot_env_data_Downs,
       bg = "white",
       width = 10,
       height = 10,
       dpi = 300)

ggsave(filename = file.path("plots/", "env_Shetland_Orkneys.png"),
       plot = plot_env_data_Shetland_Orkneys,
       bg = "white",
       width = 10,
       height = 10,
       dpi = 300)
```
