---
title: "readme_R"
author: "finn krauss"
date: "2025-05-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The folder R contains all the R code used in this project.

-   **data_cleanup.Rmd** contains the R code to import and clean all necessary data from the "data raw" folder. The imported Data is saved to the "data" folder in the .Rdata format. In addition, Plots for a first glance and evaluation of the data are generated and saved to the "plots" folder.

    -   Use: Import raw data, save clean data & generate first plots.

-   **data_analysis** contains the R code to analyse the data for regimes shifts, it imports its data from "data" and uses functions of the "functions" file.

    -   Use: Import and analyse data for regmie-shifts

-   **functions** contains the definition of various functions to cluttered the main code files.

    -   use: defines functions used in "data_cleanup" & "data_analysis"

-   **tipping_northsea_fish-main.zip** contains the R code used for the paper ["Regime shift dynamics, tipping points and the success of fisheries management" by Blöcker et al. 2023](doi.org/10.1038/s41598-022-27104-y) .

    -   Use: It includes code used in the analysis for change points (Spawning Stock Biomass (SSB)), hysteresis and Stock Recruitment Relationship (SRR).
    -   Link: <https://github.com/HeleneGutte/tipping_northsea_fish/tree/main>
