---
title: "README"
output: html_document
date: "2025-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The data raw Folder includes all data as it was received from its various sources. The data was received in May / June 2025.

### Environmental Data

-   **Global SST Monthly Mean.nc** was fetched from the NOAA Physical Sciences Laboratory. It contains SST data interpolated with the Optimal Interpolation (OI) model.

    -   Type: Sea Surface Temperature (SST), daily data condensed to monthly average

    -   Coverage: Global

    -   Time Range: 09.1981 to 05.2025

    -   Resolution: 0.25° x 0.25°

    -   Link: <https://psl.noaa.gov/data/gridded/data.noaa.oisst.v2.highres.html>

-   **NS SST Monthly.nc** was fetched from the Copernicus Marine MyOcean platform. It contains SST data of the North Sea interpolated with the NEMO model.

    -   Type: SST on a monthly scale

    -   Coverage: North Sea

    -   Time Range 01.1993 to 01.2024

    -   Resolution: 0.111° x 0.067°

    -   Link: <https://data.marine.copernicus.eu/viewer/expert?view=dataset&dataset=NWSHELF_MULTIYEAR_PHY_004_009>

-   **NS SBT Monthly.nc** was fetched from the Copernicus Marine MyOcean platform. It contains SBT data of the North Sea interpolated with the NEMO model.

    -   Type: Sea Bottom Temperature (SBT) on a monthly scale

    -   Coverage: North Sea

    -   Time Range 01.1993 to 01.2024

    -   Resolution: 0.111° x 0.067°

    -   Link: <https://data.marine.copernicus.eu/viewer/expert?view=dataset&dataset=NWSHELF_MULTIYEAR_PHY_004_009>

-   **NS SSS Monthly.nc** was fetched from the Copernicus Marine MyOcean platform. It contains SSS data of the North Sea interpolated with the NEMO model.

    -   Type: Sea Surface Salinity (SSS) on a monthly scale

    -   Coverage: North Sea

    -   Time Range 01.1993 to 01.2024

    -   Resolution: 0.111° x 0.067°

    -   Link: <https://data.marine.copernicus.eu/viewer/expert?view=dataset&dataset=NWSHELF_MULTIYEAR_PHY_004_009>

-   **NSAS LAI.txt** contains Larva Abundance Index data for the North Sea Herring (*Clupea Harengus*). It was received from Niels T. Hintzen of the Pelagic Freezer Trawler Association (PFA).

    -   Type:

    -   Time Range:

-   **NSAS LAI Components.csv** contains component specific LAI data for the North Sea Herring. It was received from Niels T. Hintzen of the Pelagic Freezer Trawler Association (PFA).

    -   Type:

    -   Time Range:

-   **NSAS SSB 2025.csv** contains Spawning Stock Biomass data for the North Sea Herring. It was received from Niels T. Hintzen of the Pelagic Freezer Trawler Association (PFA).

    -   Type:

    -   Time Range:
